import React from 'react'

function Governance() {
    return (
        <section className="dark:bg-black dark:text-white h-calc">
            <div className="container p-4">
                <h1 className="mb-4 text-4xl font-semibold leading-10 tracking-wide text-center text-indigo-500 sm:text-6xl font-Roboto">Governance</h1>
                <div className="max-w-2xl mx-auto">
                    <div>
                        <article className="mb-8">
                            <div className="py-4">
                                <h2 className="mb-4 text-3xl sm:text-4xl font-Roboto ">On-chain voting</h2>
                                <p className="text-lg">
                                    PROFIT token holders with sufficient voting power can directly participate in the governance of the Stability protocol. These will be the only investors who can collectively change the organization’s resource distribution (mentioned below) and participate in critical decision-making processes involving the direction of the entire ecosystem.
                                </p>
                            </div>
                        </article>
                    </div>
                </div>
                <div className="max-w-2xl mx-auto">
                    <article >
                        <div className="w-full mb-7">
                            <h2 className="mb-4 text-3xl sm:text-4xl font-Roboto ">Resource distribution</h2>
                            <p className="text-lg">
                                All profits generated by the organization through <i>Profit Generation</i> are divided between the token stakers, the development fund, and non-profit activities. Governance can change this allocation by following the criteria below:
                            </p>
                        </div>
                        <table className="w-full mx-auto text-sm table-auto bg-blend-darken md:text-xl">
                            <thead>
                            <tr>
                                <th className="w-1/4 text-left">Profit Earner</th>
                                <th className="w-1/4">Contract</th>
                                <th className="w-1/4 text-center">Current share</th>
                                <th className="w-1/4 text-right">Limits</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td className="py-1">Users</td>
                                <td className="py-1 pl-1">DividendPayer</td>
                                <td className="py-1 font-bold text-center">97%</td>
                                <td className="py-1 text-right whitespace-nowrap">50% - 99%</td>
                            </tr>
                            <tr>
                                <td className="py-1">Builders</td>
                                <td className="py-1 pl-1">DevFund</td>
                                <td className="py-1 font-bold text-center">2.5%</td>
                                <td className="py-1 text-right whitespace-nowrap">1% - 50%</td>
                            </tr>
                            <tr>
                                <td className="py-1">People in need</td>
                                <td className="py-1 pl-1">NonProfit</td>
                                <td className="py-1 font-bold text-center">0.5%</td>
                                <td className="py-1 text-right whitespace-nowrap">0.5% - 25%</td>
                            </tr>
                            </tbody>
                        </table>
                    </article>
                </div>
            </div>

        </section>
    )
}

export default Governance