export { default as Home } from './Home'
export { default as Governance } from './Governance'
export { default as Team } from './About'
export { default as Tokens } from './Tokens'
export { default as Dividends } from './Dividends'
export { default as Faq } from './Faq'
export { default as ProfitMaker } from './ProfitMaker'