export {default as Home} from './Home'
export {default as Development} from './Development'
export {default as Pools} from './Pools'
export {default as Generation} from './Generation'
export {default as Governance} from './Governance'
export {default as Team} from './Team'
export {default as Tokens} from './Tokens'
export {default as Dividends} from './Dividends'