import React from 'react'

function Ecosystem(){

    return (
        <section className="dark:bg-black dark:text-white h-calc">
            <div className="container w-11/12 py-8">
                <h1 className="mb-4 text-4xl font-semibold leading-10 tracking-wide text-center text-indigo-500 sm:text-6xl font-Roboto">Ecosystem</h1>
                <ul className="p-4 lg:p-8 ">
                    <li>
                        <article>
                            <a className="p-4 lg:p-6 ">
                                <h1 className="mb-4 text-4xl sm:text-5xl font-Roboto ">Token</h1>
                                <p className="ml-8 ">
                                    The native token PROFIT's primary purpose is to represent ownership shares of the Stability protocol. Given PROFIT holders are effectively owners of Stability, they will be entitled to a share of any additional profits generated by the protocol. Holding the token also allows investors to manage the Stability protocol collectively. Once the PROFIT token is fully minted and distributed in Phase 1, it will become deflationary.
                                </p>
                            </a>
                        </article>
                    </li>
                    <li>
                        <article>
                            <a className="p-4 overflow-hidden rounded-xl lg:p-6 ">
                                <h1 className="mb-4 text-4xl sm:text-5xl font-Roboto ">Governance</h1>
                                <p className="ml-8 ">
                                    PROFIT token holders with sufficient voting power can directly participate in the governance of the Stability protocol. These will be the only investors who can collectively change the organization’s resource distribution (mentioned below) and participate in critical decision-making processes involving the direction of the entire ecosystem.
                                </p>
                            </a>
                        </article>
                    </li>
                    <li>
                        <article>
                            <a className="p-4 overflow-hidden rounded-xl lg:p-6 ">
                                <h1 className="mb-4 text-4xl sm:text-5xl font-Roboto ">Builders</h1>
                                <p className="ml-8 ">
                                    <i>Stability Builders</i> are skilled individuals who directly contribute to the advancement of the entire ecosystem. These include github contributors (open-source developers), expert researchers from a variety of fields, top public relations & marketing personnel, and cybersecurity specialists.<br/>
                                    Governance will be tasked with creating the optimal conditions that allow these highly qualified contributors to build and improve upon the protocol at maximum efficiency.
                                </p>
                            </a>
                        </article>
                    </li>
                    <li>
                        <article>
                            <a className="p-4 overflow-hidden rounded-xl lg:p-6 ">
                                <h1 className="mb-4 text-4xl sm:text-5xl font-Roboto ">Generation</h1>
                                <p className="ml-8 ">
                                    <i>Profit Generation</i> is a broad term that encapsulates the process of delivering through developments a high level of value that’s necessary to earn profits. The process involves <i>Stability Builders</i> creating work units (smart contracts and decentralized applications) that become property of the Stability protocol and will essentially work for it. Clusters of work units (e.g. yield farms with a variety of features, AMMs, NFTs, etc.) being utilized in the same area are called <i>Profit Generators</i>.
                                </p>
                            </a>
                        </article>
                    </li>
                    <li>
                        <article>
                            <a className="p-4 overflow-hidden rounded-xl lg:p-6 ">
                                <h1 className="mb-4 text-4xl sm:text-5xl font-Roboto ">Resource distribution</h1>
                                <p className="ml-8 ">
                                    All profits generated by the organization through <i>Profit Generation</i> are divided between the token holders (98% at launch), the development fund (1.5%), and non-profit activities (0.5%). Governance can change this allocation by following the criteria below:
                                </p>
                            </a>
                            <ol className="ml-16 list-disc">
                                <li>Profit for stakeholders - min 50%, max 99%</li>
                                <li>Resources for builders - min 0.5%, max 50%</li>
                                <li>Non-profit activity - min 0.5%, max 25%</li>
                            </ol>
                        </article>
                    </li>
                </ul>
            </div>
        </section>
    )
}

export default Ecosystem
