import React from 'react'

function Ecosystem(){

    return (
        <section className="dark:bg-black dark:text-white h-calc">
            <div className="container w-11/12 py-8">
                <h1 className="mb-4 text-4xl font-semibold leading-10 tracking-wide text-center text-indigo-500 sm:text-6xl font-Roboto">Ecosystem</h1>
                <ul className="p-4 lg:p-8 ">
                    <li>
                        <article>
                            <a className="p-4 lg:p-6 ">
                                <h1 dateTime="" className="mb-4 text-4xl sm:text-5xl font-Roboto ">Token</h1>
                                <p className="ml-8 ">The token is used for ownership, management and profit making.<br/>
                                    Fully minted and distributed in Phase 1, it becomes deflationary.<br/>
                                    The owners of the organization are all token holders. They can use their tokens to get their share of the profits generated by the organization.</p>
                            </a>
                        </article>
                    </li>
                    <li>
                        <article>
                            <a className="p-4 overflow-hidden rounded-xl lg:p-6 ">
                                <h1 dateTime="" className="mb-4 text-4xl sm:text-5xl font-Roboto ">Governance</h1>
                                <p className="ml-8 ">Token holders who have sufficient voting power can participate in the governance of the organization. Only they can change the distribution of profits.
                                </p>
                            </a>
                        </article>
                    </li>
                    <li>
                        <article>
                            <a className="p-4 overflow-hidden rounded-xl lg:p-6 ">
                                <h1 dateTime="" className="mb-4 text-4xl sm:text-5xl font-Roboto ">Builders</h1>
                                <p className="ml-8 ">Stability Builders are our github contributors - open source developers, researchers and specialists - who directly advance the organization. These people should spend maximum time at work in the organization. Governance must create the right conditions for this.
                                </p>
                            </a>
                        </article>
                    </li>
                    <li>
                        <article>
                            <a className="p-4 overflow-hidden rounded-xl lg:p-6 ">
                                <h1 dateTime="" className="mb-4 text-4xl sm:text-5xl font-Roboto ">Generation</h1>
                                <p className="ml-8 ">To get profit in the crypto industry by an organization, builders create work units - computer programs (smart contracts and decentralized applications). Once launched, the units become the property of the organization and work for it. Clusters of units working in the same area of the crypto-economy are called Profit Generators.
                                </p>
                            </a>
                        </article>
                    </li>
                    <li>
                        <article>
                            <a className="p-4 overflow-hidden rounded-xl lg:p-6 ">
                                <h1 dateTime="" className="mb-4 text-4xl sm:text-5xl font-Roboto ">Resource distribution</h1>
                                <p className="ml-8 ">All the generated profit of the organization is divided between the token holders (98% at launch), the development fund (1.5%) and non-profit activities (0.5%). Governance can change this ratio, but with restrictions :
                                </p>
                            </a>
                            <ol className="ml-12 list-disc">
                                <li>Profit for stakeholders - min 50%, max 99%</li>
                                <li>Resources for builders - min 0.5%, max 50%</li>
                                <li>Non-profit activity - min 0.5%, max 25%</li>
                            </ol>
                        </article>
                    </li>

                </ul>


            </div>
        </section>
    )
}

export default Ecosystem
